### ISSUE TITLE
Moving towards semantic versioning

### ISSUE THREAD

**Issue by MolassesLover** [Mori-TM/Magma-Engine#4]
Currently this project exclusively uses major version numbers, such as `v5.0` and `v6.0`. This is not very descriptive; it will cause headaches, and it already has caused trouble when it comes to the creation of my pull request.

Additionally, the project uses branches for versioning rather than tags. This means one would have to port their pull request to each branch, and manually resolve endless amounts of merge conflicts.

My recommendation is that you move away from creating branches for version numbers, move to tags, and begin creating GitHub releases.

**Comment by Mori-TM** [comment]
Done!
